#!/bin/bash

DET=$1
RUN=$2
PSRIN=$3
NINST=$4
NINJ=$5

arg=("$DET" "$RUN" "$PSRIN" "$NINST" "$NINJ")

./analysis_gauss/writedag_full_gauss.py "${arg[@]}"

condor_submit_dag dags/fullgauss_"$DET""$RUN"_"$PSRIN".dag
